name: Deploy Test

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Rust project

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

  tests:
    runs-on: ubuntu-latest
    name: Run tests

    steps:
      - uses: actions/checkout@v3

      - name: Setup Postgres
        uses: ikalnytskyi/action-setup-postgres@v4

      - name: Run tests
        run: cargo test --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: [build, tests]
    name: Deploy to test Docker Hub

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: stslex/proselection:test
          platforms: linux/amd64
          context: .

  run_server:
    runs-on: ubuntu-latest
    needs: [deploy]
    name: Run server on remote

    steps:
      - name: SSH Command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH }}
          script: |
            cd rust_server
            docker compose pull rproselection_test
            docker compose down rproselection_test
            docker compose up rproselection_test -d
